name: neat
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10.*
  - biopython=1.79
  - pkginfo
  - matplotlib
  - numpy
  - pyyaml
  - pip
  - scipy
  - libgcc=5.2.0
  - htslib
  - pysam
  - frozendict
  - poetry
  - pandas
